FROM maven:3.9.9-eclipse-temurin-21-alpine AS build
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests -Dquarkus.container-image.build=false

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

COPY --from=build /build/target/quarkus-app/ ./

ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0"

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "quarkus-run.jar"]